In [7]:
!pip3 install numpy

In [10]:
import numpy as np

In [9]:
np.__version__

'1.18.5'

In [11]:
a = np.array([1,2,3,4,5])

In [12]:
a

array([1, 2, 3, 4, 5])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2,11,3)

array([2, 5, 8])

In [18]:
c = np.array([[1,2],[3,4],
             [5,6],[7,8]])

In [19]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
c.shape

(4, 2)

In [21]:
c.ndim

2

#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

In [22]:
d = np.arange(0,21,1)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


#2.呈上題，將以上數列取出偶數。

In [31]:
for i in range(0,21,2):
    print(i)

0
2
4
6
8
10
12
14
16
18
20


#3.呈1題，將數列取出3的倍數。

In [32]:
for i in range(0,21,3):
    print(i)

0
3
6
9
12
15
18
