題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [1]:
import numpy as np

In [10]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
#是，雖然算出來沒有完全等於[[1,0],[0,1]]，因為反矩陣計算浮點數的關係所以不會完全等於
array1 = np.array([[10, 8], [3, 5]])
array1_inv = np.linalg.inv(array1)
print(array1@array1_inv)

[[1. 0.]
 [0. 1.]]


In [11]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array1)
print("eigenvalues :",w)
print("eigenvactors :",v)

eigenvalues : [13.  2.]
eigenvactors : [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [4]:
#3. 運用上列array計算SVD?
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))